name: MLflow Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install DVC
      run: pip install dvc

    - name: Install other dependencies
      run: pip install -r requirements.txt
      
    - name: Configure Google Drive remote
      run: dvc remote add -f gdrive gdrive:1TcslBQ2BQ5kNbIYLbQENGpW1UfrR1rH-
      
    - name: Pull DVC-tracked data
      run: |
 
            dvc remove MLOPS-FYP/route_github.csv.dvc
            dvc remove CompleteJourney_update.csv.dvc
            dvc remove MLOPS-FYP/cargo_data.csv.dvc
            dvc remove MLOPS-FYP/route_data.csv.dvc
            dvc remove MLOPS-FYP/speed_bounds_update.csv.dvc
            dvc pull 


    - name: Train models
      run: python Vs_anomaly.py

   
