name: MLflow Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install DVC
      run: pip install dvc
    - name: Install mlfow
      run: pip install mlflow
      
    - name: Install airflow
      run: pip install apache-airflow

    - name: Install other dependencies
      run: pip install -r requirements.txt
      
    - name: Configure Google Drive remote
      run: dvc remote add -f gdrive gdrive:1TcslBQ2BQ5kNbIYLbQENGpW1UfrR1rH-
      
    - name: Pull DVC-tracked data
      run: |
        pip install --upgrade pathspec
        dvc pull MLOPS-FYP/route_github.csv


    - name: Train models
      run: python ml_air_flow_for_route.py

   
