name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC
        run: |
          pip install dvc
          dvc init
          dvc remote add -d mydrive gdrive://your_drive_id

      - name: Pull DVC data
        run: dvc pull
        
      - name: Load DVC datasets
        run: |
          dvc import dataset1.dvc data/
          dvc import dataset2.dvc data/
          
      - name: Run training
        run: |
          python train_model1.py --data ../data/dataset1.csv
          python train_model2.py --data ../data/dataset2.csv

      - name: Save models to DVC
        run: |
          cd ..
          dvc add model1.pkl
          dvc add model2.pkl
          dvc push

      - name: Deploy Flask app
        run: |
          python app.py
