name: Train and Deploy Model

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python vs_anomaly.py --data route_github.csv
        
      - name: Copy model to Flask app
        run: cp modelroute.h5 app/

      - name: Set up Flask environment
        run: |
          cd app/
        

      - name: Run Flask app
        run: |
          cd app/
          pip install -r requirements.txt
          python server.py
#       - name: Deploy to Flask app
#         uses: peaceiris/actions-gh-pages@v3
    
