name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up DVC
        run: |
          pip install dvc
          dvc init
          dvc remote add -d mydrive gdrive://1TcslBQ2BQ5kNbIYLbQENGpW1UfrR1rH-

      - name: Pull DVC data
        run: dvc pull
        
      - name: Load DVC datasets
        run: |
          dvc import route_github.csv.dvc MLOPS-FYP/
      
          
      - name: Run training
        run: |
          python vs_anomaly.py --data ../MLOPS-FYP/route_github.csv
         

      - name: Save models to DVC
        run: |
          cd ..
          dvc add model_route.pkl

          dvc push

      - name: Deploy Flask app
        env:
          MODEL1_PATH: models/model_route.pkl
        
        run: |
          python server.py
