name: Train and Deploy Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python vs_anomaly.py
        
      - name: Copy model to Flask app
        run: cp model.pkl app/

      - name: Set up Flask environment
        run: |
          cd app/
          pip install -r requirements.txt

      - name: Run Flask app
        run: |
          cd app/
          python app.py
#       - name: Deploy to Flask app
#         uses: peaceiris/actions-gh-pages@v3
    
